### ISSUE TITLE
Try to get a paddle by drawing small line on the screen

### ISSUE THREAD

**Issue by Bhagyashree-Rawal** [contact-tracer-csci-526/contact-tracer#20]
May be get a starting and ending click location and draw  a paddle at that location

**Comment by RuchaTambe** [comment]
https://www.youtube.com/watch?v=pa_U64G7gkE

**Comment by eldeni** [comment]
Done, closing

**Comment by jungwony629** [comment]
Drawing line using a finger :)
https://answers.unity.com/questions/377596/how-do-you-draw-a-line-using-your-finger-on-androi.html

**Comment by eldenpark** [comment]
@Bhagyashree-Rawal @RuchaTambe Seems to be done? At least the draft?

**Comment by RuchaTambe** [comment]
> @Bhagyashree-Rawal @RuchaTambe Seems to be done? At least the draft?

@eldeni yes it is done. Changes exist in the branch: rucha_tambe_line_drawing. Need to merge that branch with the master, after getting it up to date with changes

**Comment by eldenpark** [comment]
> > @Bhagyashree-Rawal @RuchaTambe Seems to be done? At least the draft?
> 
> @eldeni yes it is done. Changes exist in the branch: rucha_tambe_line_drawing. Need to merge that branch with the master, after getting it up to date with changes

Gotcha. Take your time and let us know if there's something unclear while merging

**Comment by RuchaTambe** [comment]
> > > @Bhagyashree-Rawal @RuchaTambe Seems to be done? At least the draft?
> > 
> > 
> > @eldeni yes it is done. Changes exist in the branch: rucha_tambe_line_drawing. Need to merge that branch with the master, after getting it up to date with changes
> 
> Gotcha. Take your time and let us know if there's something unclear in merging

Sure

**Comment by eldenpark** [comment]
Done. closing
