### ISSUE TITLE
Port the app on mobile phone

### ISSUE THREAD

**Issue by RuchaTambe** [contact-tracer-csci-526/contact-tracer#23]
Tested the app on an Android phone: 
Observations:
1. The balls escape the screen, collide with the virus outside the screen frame and return as viruses.
2. The velocity of balls is too high.
3. Line drawing feature works well, as of now.

**Comment by eldenpark** [comment]
#21

**Comment by eldenpark** [comment]
Both tested on ios/android devices. Done
