### ISSUE TITLE
Ball velocity after colling with each other; constant speed is to be expected

### ISSUE THREAD

**Issue by eldenpark** [contact-tracer-csci-526/contact-tracer#24]
Constant speed is to be expected even when it is hit by others with different velocities

**Comment by eldenpark** [comment]
@patrick-assaf Let us know if you get stuck upon any problem

**Comment by jungwony629** [comment]
https://answers.unity.com/questions/170362/keep-constant-velocity.html

**Comment by gmoncada001** [comment]
Completed
