### ISSUE TITLE
Cure ball and ball freezing funtionality - 1st implementation [RFC]

### ISSUE THREAD

**Issue by RuchaTambe** [contact-tracer-csci-526/contact-tracer#49]
*Request for comments*

## Ball Freezing
- Freeze two balls, at any time during the gameplay - in order to allow "tap" of the loader functionality for other infected balls.
- The freeze functionality is done by drawing a circle around the ball to be frozen.

## Cure balls
Cure ball appears after (say) 15 seconds on the game scene. It moves randomly around the screen for 5 seconds. During this time, any infected ball (excluding the original virus) that collides with the cure ball gets converted to normal ball.
- Collisions with cure ball can be made by draw line mechanism.
- Limit of the length of line that can be drawn by user is equivalent to the circumference of the circle.

**Comment by RuchaTambe** [comment]
Add cure ball after 20 seconds, into the game. Allow infected balls to be cured by dragging them towards the cure ball

**Comment by eldenpark** [comment]
edited

**Comment by RuchaTambe** [comment]
Thanks Elden!
