### ISSUE TITLE
Improve SafeBall functionality

### ISSUE THREAD

**Issue by RuchaTambe** [contact-tracer-csci-526/contact-tracer#65]
1. When circle is drawn around a normal ball (to convert it to a safe ball), 

-  Remove RigidBody 2D component of the SafeBall for a specific amount of time.

- Reduce opacity of the safe ball

- Restore original behavior after 3 secs (display 3,2,1) on the ball itself.

**Comment by eldenpark** [comment]
Is it being taken care of? or done?

**Comment by eldenpark** [comment]
Done. Closing
